import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<link
  href="https://cdn.jsdelivr.net/npm/keen-slider@6.8.6/keen-slider.min.css"
  rel="stylesheet"
/>;
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
